import { useMemo, useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ScrollView, Text, View } from "react-native";
import { Button, Calendar, Input, Modal, Select } from "@/shared/components";
import { AdminSectionCard } from "../AdminSectionCard";
import { reservaZonaEditSchema } from "../../schemas/reservasZona.schema";
import type { ReservaZonaEditValues } from "../../types/reservasZona";
import { useAdministradorReservasZona } from "../../hooks/useAdministradorReservasZona";
import { useZonasStore } from "@/stores";
export function GestionZonaReservasView({ id, onBack, onCreate }: { id: string; onBack: () => void; onCreate: (depto: string) => void }) {
  const zona = useZonasStore((state) => state.gestionZonas[id]);
  const { data: allReservations = [], updateEstado, updateReserva, deleteReserva } = useAdministradorReservasZona(id);
  const [filterDate, setFilterDate] = useState<Date | null>(null); const [showDate, setShowDate] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [department, setDepartment] = useState(""); const [detail, setDetail] = useState<any>(null); const [editing, setEditing] = useState<any>(null); const [canceling, setCanceling] = useState<any>(null); const [deleting, setDeleting] = useState<any>(null);
  const { control, handleSubmit, reset } = useForm<ReservaZonaEditValues>({ resolver: zodResolver(reservaZonaEditSchema), defaultValues: { nombre: "", depto: "", fecha: "", horario: "", comentarios: "" } });
  const reservations = useMemo(() => filterDate ? allReservations.filter((item) => !item.fecha || item.fecha === filterDate.toISOString().slice(0, 10)) : allReservations, [allReservations, filterDate]);
  const startEdit = (reservation: any) => { setEditing(reservation); reset({ nombre: reservation.nombre || "", depto: reservation.depto || "", fecha: reservation.fecha || "", horario: reservation.horario || "", comentarios: reservation.comentarios || "" }); };
  return <><ScrollView className="flex-1" contentContainerClassName="p-4 gap-4"><Button variant="secondary" fullWidth onPress={onBack}>Volver a zonas</Button><Button fullWidth onPress={() => setCreateOpen(true)}>Crear reserva</Button><AdminSectionCard title="Filtros"><Button variant="secondary" fullWidth onPress={() => setShowDate(true)}>{filterDate ? `Fecha: ${filterDate.toLocaleDateString("es-AR")}` : "Filtrar por fecha"}</Button>{filterDate && <Button variant="ghost" fullWidth onPress={() => setFilterDate(null)}>Limpiar filtro</Button>}</AdminSectionCard><AdminSectionCard title="Reservas registradas">{reservations.length ? reservations.map((reservation) => <View key={reservation.id} className="border-b border-gray-100 py-3 gap-2"><Text className="text-sm font-semibold text-gray-900">{reservation.nombre || reservation.depto || "Reserva"}</Text><Text className="text-xs text-gray-500">{reservation.depto} · {reservation.fecha || "Sin fecha"} · {reservation.horario}</Text><Text className="text-xs text-gray-500">Reserva N° {reservation.reservaNum}</Text><Select value={reservation.estado} options={["Reservado", "Aprobado", "Pendiente", "Rechazado", "Cancelada"]} onChange={(value) => updateEstado({ id: reservation.id, estado: String(value) })} /><View className="flex-row gap-2"><Button size="sm" variant="secondary" onPress={() => setDetail(reservation)}>Detalle</Button><Button size="sm" variant="secondary" onPress={() => startEdit(reservation)}>Editar</Button><Button size="sm" variant="ghost" onPress={() => setCanceling(reservation)}>Cancelar</Button><Button size="sm" variant="danger" onPress={() => setDeleting(reservation)}>Eliminar</Button></View></View>) : <Text className="text-sm text-gray-500 text-center">No hay reservas para esta zona.</Text>}</AdminSectionCard></ScrollView>
    <Modal visible={createOpen} onClose={() => setCreateOpen(false)} title="Nueva Reserva"><View className="gap-4"><Text className="text-sm text-gray-500">Selecciona el departamento para continuar con la reserva.</Text><Input label="Departamento" value={department} onChangeText={setDepartment} placeholder="Ej: T1-101" /><Button fullWidth disabled={!department.trim()} onPress={() => { setCreateOpen(false); onCreate(department.trim()); setDepartment(""); }}>Continuar</Button></View></Modal>
    <Modal visible={!!detail} onClose={() => setDetail(null)} title="Detalle de Reserva"><View className="gap-3"><Text className="text-sm text-gray-500">Residente</Text><Text className="text-base font-semibold text-gray-900">{detail?.nombre || detail?.residenteNombre || "-"}</Text><Text className="text-sm text-gray-500">Departamento</Text><Text className="text-base text-gray-900">{detail?.depto || "-"}</Text><Text className="text-sm text-gray-500">Fecha y horario</Text><Text className="text-base text-gray-900">{detail?.fecha || "-"} · {detail?.horario || "-"}</Text><Text className="text-sm text-gray-500">Estado</Text><Text className="text-base text-gray-900">{detail?.estado || "-"}</Text></View></Modal>
    <Modal visible={!!editing} onClose={() => setEditing(null)} title="Editar Reserva"><View className="gap-3"><Controller control={control} name="nombre" render={({ field }) => <Input label="Nombre" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="depto" render={({ field }) => <Input label="Departamento" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="fecha" render={({ field }) => <Input label="Fecha" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="horario" render={({ field }) => <Input label="Horario" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="comentarios" render={({ field }) => <Input label="Observaciones" value={field.value} onChangeText={field.onChange} multiline rows={3} />} /><Button fullWidth onPress={() => void handleSubmit((value) => { if (editing) updateReserva({ id: editing.id, datos: value }); setEditing(null); })()}>Guardar cambios</Button></View></Modal>
    <Modal visible={!!canceling} onClose={() => setCanceling(null)} title="Cancelar Reserva"><View className="gap-4"><Text className="text-base text-gray-900 text-center">¿Deseas cancelar esta reserva?</Text><Button variant="danger" fullWidth onPress={() => { if (canceling) updateEstado({ id: canceling.id, estado: "Cancelada" }); setCanceling(null); }}>Cancelar reserva</Button><Button variant="ghost" fullWidth onPress={() => setCanceling(null)}>Volver</Button></View></Modal>
    <Modal visible={!!deleting} onClose={() => setDeleting(null)} title="Eliminar Reserva"><View className="gap-4"><Text className="text-base text-gray-900 text-center">Esta accion no puede deshacerse.</Text><Button variant="danger" fullWidth onPress={() => { if (deleting) deleteReserva(deleting.id); setDeleting(null); }}>Eliminar</Button><Button variant="ghost" fullWidth onPress={() => setDeleting(null)}>Cancelar</Button></View></Modal>
    <Modal visible={showDate} onClose={() => setShowDate(false)} title="Seleccionar fecha"><Calendar selected={filterDate} onSelect={(date) => { setFilterDate(date); setShowDate(false); }} /></Modal>
  </>;
}
