import { useEffect } from "react";
import { Controller, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button, Input, Toggle } from "@/shared/components";
import { Text, View } from "react-native";
import type { Coadministrador } from "@/shared/types";
import { coadministradorSchema } from "../../schemas/coadministradores.schema";
import { PERMISOS_COADMIN, permisosCoadministradorIniciales, type CoadministradorFormValues } from "../../types/coadministradores";
export function CoadministradorForm({ editing, onSave }: { editing: Coadministrador | null; onSave: (value: CoadministradorFormValues) => void }) { const initial: CoadministradorFormValues = { nombre: editing?.nombre || "", apellido: editing?.apellido || "", correo: editing?.correo || editing?.email || "", celular: editing?.celular || "", permisos: { ...permisosCoadministradorIniciales(), ...(editing?.permisos || {}) } }; const { control, handleSubmit, reset } = useForm<CoadministradorFormValues>({ resolver: zodResolver(coadministradorSchema), defaultValues: initial }); useEffect(() => reset(initial), [editing, reset]); return <View className="gap-3"><Controller control={control} name="nombre" render={({ field }) => <Input label="Nombre *" placeholder="Nombre" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="apellido" render={({ field }) => <Input label="Apellido" placeholder="Apellido" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="correo" render={({ field }) => <Input label="Correo electrónico *" placeholder="correo@ejemplo.com" type="email" value={field.value} onChangeText={field.onChange} />} /><Controller control={control} name="celular" render={({ field }) => <Input label="Celular" placeholder="+593 999999999" value={field.value} onChangeText={field.onChange} />} /><View className="rounded-xl border border-gray-200 bg-gray-50 p-3 gap-2"><Text className="text-sm font-bold text-gray-900">Permisos</Text><Text className="text-xs leading-4 text-gray-500">Activa o desactiva cada acceso. Los de visualización son solo lectura; los de gestión permiten crear y editar.</Text>{PERMISOS_COADMIN.map(([key, label, description]) => <View key={key} className="flex-row items-start justify-between gap-3 border-t border-gray-200 py-2"><View className="flex-1"><Text className="text-sm font-semibold text-gray-900">{label}</Text><Text className="mt-0.5 text-xs leading-4 text-gray-500">{description}</Text></View><Controller control={control} name={`permisos.${key}`} render={({ field }) => <Toggle value={!!field.value} onChange={field.onChange} />} /></View>)}</View><Button fullWidth onPress={() => void handleSubmit(onSave)()}>{editing ? "Guardar cambios" : "Agregar coadministrador"}</Button></View>; }
