export * from "./arquitectura.schema";
export * from "./seguridad.schema";
export * from "./ubicacion.schema";
export * from "./zonas.schema";
export * from "./gestionZona.schema";
export * from "./reservasZona.schema";
export * from "./permisos.schema";
export * from "./reportes.schema";
export * from "./coadministradores.schema";
