import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FILTROS_ESTADO } from "@/data";
import type { CorrespondenciaItem } from "@/shared/types";
import { createCorrespondenciaRequest, deleteCorrespondenciaRequest, fetchCorrespondenciaRequest, updateCorrespondenciaRequest } from "../services/correspondencia.service";
import { useCorrespondenciaFeatureStore } from "../stores/correspondencia.store";
export const correspondenciaQueryKey = ["correspondencia"] as const;
export function useCorrespondencia() { const queryClient = useQueryClient(); const query = useQuery({ queryKey: correspondenciaQueryKey, queryFn: fetchCorrespondenciaRequest, initialData: useCorrespondenciaFeatureStore.getState().items }); const createMutation = useMutation({ mutationFn: createCorrespondenciaRequest, onSuccess: (item) => { useCorrespondenciaFeatureStore.getState().agregar(item); void queryClient.invalidateQueries({ queryKey: correspondenciaQueryKey }); } }); const updateMutation = useMutation({ mutationFn: updateCorrespondenciaRequest, onSuccess: ({ id, estado, extras }) => { useCorrespondenciaFeatureStore.getState().actualizarEstado(id, estado, extras); void queryClient.invalidateQueries({ queryKey: correspondenciaQueryKey }); } }); const deleteMutation = useMutation({ mutationFn: deleteCorrespondenciaRequest, onSuccess: (id) => { useCorrespondenciaFeatureStore.getState().eliminar(id); void queryClient.invalidateQueries({ queryKey: correspondenciaQueryKey }); } }); return { ...query, items: query.data || [], agregar: createMutation.mutate, actualizarEstado: updateMutation.mutate, eliminar: deleteMutation.mutate }; }
export function useCorrespondenciaFiltros(items: CorrespondenciaItem[]) { const [search, setSearch] = useState(""); const [estadoSeleccionados, setEstadoSeleccionados] = useState<string[]>([]); const [filterOpen, setFilterOpen] = useState(false); const [catFilter, setCatFilter] = useState(""); const [entregaFilter, setEntregaFilter] = useState(false); const [fechaDesde, setFechaDesde] = useState("2025-05-14"); const [fechaHasta, setFechaHasta] = useState("2025-07-30"); const toggleEstado = (value: string) => setEstadoSeleccionados((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); const toggleTodos = () => setEstadoSeleccionados((current) => current.length === 0 || current.length === FILTROS_ESTADO.length ? [] : FILTROS_ESTADO.map((filter) => filter.value)); const filtered = useMemo(() => items.filter((item) => { const normalized = search.toLowerCase(); const matchSearch = !normalized || item.nombre.toLowerCase().includes(normalized) || item.empresa.toLowerCase().includes(normalized); const matchStatus = estadoSeleccionados.length === 0 || estadoSeleccionados.includes(item.estado); const matchCategory = !catFilter || item.categoria === catFilter; const matchDelivery = !entregaFilter || item.entregaEnPuerta === true; return matchSearch && matchStatus && matchCategory && matchDelivery; }), [catFilter, entregaFilter, estadoSeleccionados, items, search]); return { filtered, search, setSearch, estadoSeleccionados, toggleEstado, toggleTodos, todosActivo: estadoSeleccionados.length === 0 || estadoSeleccionados.length === FILTROS_ESTADO.length, filterOpen, setFilterOpen, fechaDesde, setFechaDesde, fechaHasta, setFechaHasta, catFilter, setCatFilter, entregaFilter, setEntregaFilter }; }
